Repository Flecher8/WeightLossApp, pull requests merged in 2022-06, with the labels that each got.

#9 Pull request for Achivement data page
  WeightLossApp/UI/wl-ui/src/Components/AchievementData/AchievementData.js
  WeightLossApp/UI/wl-ui/src/Components/ChangeAchievement/ChangeAchievement.js
  WeightLossApp/UI/wl-ui/src/Components/ChangeSection/ChangeSection.js
  WeightLossApp/UI/wl-ui/src/Components/Header/Header.js
  WeightLossApp/UI/wl-ui/src/Components/SectionTraining/SectionTraining.js
  WeightLossApp/UI/wl-ui/src/index.js
  WeightLossApp/WeightLossApp/Controllers/AchievementDataController.cs
Labels: enhancement

#10 Fix delete bug in SectionTraining
  WeightLossApp/Model/Models/Training.cs
  WeightLossApp/WeightLossApp/Controllers/SectionTrainingController.cs
Labels: bug

#11 Fixed cascade delete in table Exercise
  WeightLossApp/WeightLossApp/Controllers/ExerciseController.cs
Labels: bug

#13 Pull request for Training page
  WeightLossApp/UI/wl-ui/src/Components/ChangeTraining/ChangeTraining.js
  WeightLossApp/UI/wl-ui/src/Components/Header/Header.js
  WeightLossApp/UI/wl-ui/src/Components/Trainings/Trainings.js
  WeightLossApp/UI/wl-ui/src/index.js
  WeightLossApp/WeightLossApp/Controllers/TrainingController.cs
  WeightLossApp/WeightLossApp/appsettings.json
Labels: enhancement

#19 Page/store
  .vs/WeightLossApp/v17/.suo
  WeightLossApp/.vs/WeightLossApp/v17/TestStore/0/000.testlog
  WeightLossApp/.vs/WeightLossApp/v17/TestStore/0/testlog.manifest
  WeightLossApp/UI/wl-ui/package-lock.json
  WeightLossApp/UI/wl-ui/package.json
  WeightLossApp/UI/wl-ui/src/Components/ChangeDesignTheme/ChangeDesignTheme.js
  WeightLossApp/UI/wl-ui/src/Components/DesignTheme/DesignTheme.js
  WeightLossApp/UI/wl-ui/src/Components/Header/Header.js
  WeightLossApp/UI/wl-ui/src/Components/PremiumSubscription/PremiumSubscription.js
  WeightLossApp/UI/wl-ui/src/index.css
  WeightLossApp/UI/wl-ui/src/index.js
  WeightLossApp/WeightLossApp/Controllers/DesignThemeDataController.cs
  WeightLossApp/WeightLossApp/Controllers/PremiumSubscriptionController.cs
  WeightLossApp/WeightLossApp/WeightLossApp.csproj.user
  WeightLossApp/WeightLossApp/wwwroot/web.config
Labels: help wanted, conflict

#28 AddEventVM class Pull request
  WeightLossApp/Mobile/Mobile/ViewModels/AddEventVM.cs
  WeightLossApp/Sandbox/AddEventVM.cs
  WeightLossApp/Sandbox/Program.cs
Labels: enhancement

#29 RegistrationVM Pull Request
  WeightLossApp/Mobile/Mobile/Models/Member.cs
  WeightLossApp/Mobile/Mobile/Models/User.cs
  WeightLossApp/Sandbox/Member.cs
  WeightLossApp/Sandbox/Program.cs
  WeightLossApp/Sandbox/RegistrationVM.cs
Labels: enhancement
